export const AUTH_ROUTE = '/auth'
export const MAIN_ROUTE = '/'
export const CATEGORY_ROUTE = '/category'
export const PROFILE_ROUTE = '/profile'
export const TEST_ROUTE = '/test'
export const MISKATE_ROUTE = '/miskate'
export const FILM_ROUTE = '/film'
export const MYSUB_ROUTE = '/mySub'